server.port=9081
spring.application.name=login-service
server.address=0.0.0.0

# Database connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3307/login_DB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:login}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:login}

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.table=flyway_schema_history
spring.flyway.validate-on-migrate=true

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=BINARY


# mTLS allowlist for /internal/**
internal.mtls.allowed-callers=registration-saga-service,registration-service

# --- TLS / mTLS (server side) ---
#tls.dir=${TLS_DIR:${user.dir}/../tls}
tls.dir=${TLS_DIR:../../certificates}
keystore.password=${TLS_KEYSTORE_PASSWORD:Harlov1234!}
truststore.password=${TLS_TRUSTSTORE_PASSWORD:Harlov1234!}

spring.ssl.bundle.jks.app.keystore.location=file:${tls.dir}/login.p12
spring.ssl.bundle.jks.app.keystore.password=${keystore.password}
spring.ssl.bundle.jks.app.keystore.type=PKCS12

spring.ssl.bundle.jks.app.truststore.location=file:${tls.dir}/ca-root-keytool.p12
spring.ssl.bundle.jks.app.truststore.password=${truststore.password}
spring.ssl.bundle.jks.app.truststore.type=PKCS12

# brug bundlen på serveren
server.ssl.enabled=true
server.ssl.bundle=app
server.ssl.client-auth=need
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3
# log4j

logging.level.root=INFO 
logging.level.local.lyngberg=DEBUG 
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n


# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# i18n
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.mvc.problemdetails.enabled=true
