server.port=9099
spring.application.name=auditlog-service
server.address=0.0.0.0

# mTLS allowlist for /internal/**
internal.mtls.allowed-callers=registration-saga-service,registration-service

# --- TLS / mTLS (server side) ---
#tls.dir=${TLS_DIR:${user.dir}/../tls}
tls.dir=${TLS_DIR:../../certificates}
keystore.password=${TLS_KEYSTORE_PASSWORD:Harlov1234!}
truststore.password=${TLS_TRUSTSTORE_PASSWORD:Harlov1234!}

spring.ssl.bundle.jks.app.keystore.location=file:${tls.dir}/auditlog.p12
spring.ssl.bundle.jks.app.keystore.password=${keystore.password}
spring.ssl.bundle.jks.app.keystore.type=PKCS12

spring.ssl.bundle.jks.app.truststore.location=file:${tls.dir}/ca-root-keytool.p12
spring.ssl.bundle.jks.app.truststore.password=${truststore.password}
spring.ssl.bundle.jks.app.truststore.type=PKCS12

# brug bundlen på serveren
server.ssl.enabled=true
server.ssl.bundle=app
server.ssl.client-auth=need
server.ssl.enabled-protocols=TLSv1.2,TLSv1.3
# log4j

logging.level.root=INFO 
logging.level.local.lyngberg=DEBUG 
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n


# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# i18n
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8
spring.mvc.problemdetails.enabled=true
