-- V1__Create_audit_logs_table.sql
CREATE TABLE IF NOT EXISTS audit_logs (
    id BINARY(16) PRIMARY KEY,
    service_name VARCHAR(100) NOT NULL,
    action VARCHAR(50) NOT NULL,
    entity_type VARCHAR(255) NOT NULL,
    entity_id BINARY(16),
    user_id BINARY(16),
    user_email VARCHAR(255) NOT NULL,
    old_value TEXT,
    new_value TEXT,
    description VARCHAR(1000),
    ip_address VARCHAR(255) NOT NULL,
    user_agent VARCHAR(500),
    session_id VARCHAR(255),
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
    error_message TEXT,
    request_id VARCHAR(255),
    INDEX idx_service_name (service_name),
    INDEX idx_user_id (user_id),
    INDEX idx_user_email (user_email),
    INDEX idx_entity_type_id (entity_type, entity_id),
    INDEX idx_action (action),
    INDEX idx_status (status),
    INDEX idx_timestamp (timestamp),
    INDEX idx_service_timestamp (service_name, timestamp),
    INDEX idx_user_timestamp (user_id, timestamp)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;